# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMComponent' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'PiwikPROSDK'

  # Pods for UMComponent
  xcodeproj 'UMComponent.xcodeproj'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'UMComponentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
